name: Python package

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 2 * * WED,SAT' #runs at 2:05 UTC = 04:05 local (AMS) every Wednesday and Saturday

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  numpy pandas eurostat pycountry seaborn
      - name: excecute py script
        run: |
          python deaths.py
          
      - name: Update graphs
        run: |
          git config --global user.name 'heesters'
          git config --global user.email 'heesters@users.noreply.github.com'
          git commit -am "Update graphs"
          git push
